import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0f1321',
        'surface-dim': '#0f1321',
        'surface-container-lowest': '#0a0d1c',
        'surface-container-low': '#171b2a',
        'surface-container': '#1b1f2e',
        'surface-container-high': '#262939',
        'surface-container-highest': '#303444',
        'surface-bright': '#353849',
        'surface-variant': '#303444',
        'surface-tint': '#00dbe9',
        'on-surface': '#dfe1f6',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#dfe1f6',
        'inverse-on-surface': '#2c303f',
        'background': '#0f1321',
        'on-background': '#dfe1f6',
        'primary': '#dbfcff',
        'on-primary': '#00363a',
        'primary-fixed': '#7df4ff',
        'primary-fixed-dim': '#00dbe9',
        'primary-container': '#00f0ff',
        'on-primary-container': '#006970',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'inverse-primary': '#006970',
        'secondary': '#d1bcff',
        'on-secondary': '#3c0090',
        'secondary-container': '#7000ff',
        'on-secondary-container': '#ddcdff',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d1bcff',
        'on-secondary-fixed': '#23005b',
        'on-secondary-fixed-variant': '#5700c9',
        'tertiary': '#f4f5ff',
        'on-tertiary': '#002e6a',
        'tertiary-container': '#cad9ff',
        'on-tertiary-container': '#005ac3',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#004395',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'outline': '#849495',
        'outline-variant': '#3b494b',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        gutter: '24px',
        unit: '8px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(2deg)' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
