import type { Metadata } from "next";
import "./globals.css";
import { Bricolage_Grotesque, Space_Mono } from "next/font/google";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-heading",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-body",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.variable} ${spaceMono.variable} relative overflow-x-hidden text-white`}
      >
        {/* GLOBAL BACKGROUND */}
        <div className="global-bg" />

        {children}
      </body>
    </html>
  );
}
